### ISSUE TITLE
Cards break alignment at bigger resolutions

### ISSUE THREAD

**Issue by tekamoment** [theguidon/theguidon-twentyfifteen#57] opened 2015-08-09 15:35 UTC
Roughly after a width of >2000px the cards break the nice 3x2 grid alignment. 
<img width="1790" alt="screen shot 2015-08-09 at 11 33 53 pm" src="https://cloud.githubusercontent.com/assets/765270/9155598/3982186c-3eef-11e5-8149-708bff93c374.png">

**Comment by tekamoment** [comment] 2015-08-09 15:35
This is on Chrome on Mac, btw.

**Comment by tekamoment** [comment] 2015-08-09 15:37
Surprisingly, issue does not replicate on Firefox on Mac.
<img width="1792" alt="screen shot 2015-08-09 at 11 36 54 pm" src="https://cloud.githubusercontent.com/assets/765270/9155612/8d346776-3eef-11e5-842c-ec5ad4d8be58.png">
Issue of vendor prefixes?

**Comment by RIanDeLaCruz** [comment] 2015-08-09 15:40
@tekamoment might be the lack of wrapper

**Comment by janbelmonte** [comment] 2015-08-09 15:40
Wow, nice catch. My suspicions are:
1) vendor prefixes
2) add <div class="row"> to maintain horizontal alignment.

Will investigate further. thanks!

**Comment by janbelmonte** [comment] 2015-08-09 15:42
@RIanDeLaCruz @tekamoment 

Well the first image is too big so it's pushing down the card below it. The Beyond Loyola card is pulled up since the Sports card is too small. Not sure what happened to Inquiry.

Most likely related to #41

**Comment by RIanDeLaCruz** [comment] 2015-08-09 15:43
I've also encountered this on a smaller screen, Chrome on Ubuntu but not in Firefox

**Comment by RIanDeLaCruz** [comment] 2015-08-09 15:45
Based on the his screenshot, this and issue 41 are the same. Notice the misaligned heights

**Comment by janbelmonte** [comment] 2015-08-09 15:47
Damn dat Ubuntu shit. Will fix to avoid any disappointment from the CS community. HAHA

**Comment by janbelmonte** [comment] 2015-08-10 21:42
Closing since this is a duplicate of #41. Suggested fix is indicated there.

**Closed by janbelmonte** 2015-08-10 21:42 UTC
Labels: bug
